version: '3'

services:
  rest_infotables:
    image: traininfotables:0.1
    container_name: rest_infotables
    restart: unless-stopped
    ports:
      - 8040:8040
    command: python /app/main.py
