services:
  rest_infotables:
    image: traininfotables:1.0
    build:
      context: .
    container_name: rest_infotables
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped
    ports:
      - 8040:8040
    command: python /app/main.py
