services:
  rest_infotables:
    image: traininfotables:0.2
    build:
      context: .
    container_name: rest_infotables
    restart: unless-stopped
    ports:
      - 8040:8040
    command: python /app/main.py
